name: Build OatppServer App For Linux/Mac

on:
  push:
    branches: [ master ]
    # branches: [ master, dev ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  release:
    name: build and release app
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}

    # create a build matrix for jobs
    strategy:
      matrix:
        os: [ubuntu-latest, macos-10.15]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: python3 builddeps.py

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      # - name: Test
        # working-directory: ${{github.workspace}}/build
        # Execute tests defined by the CMake configuration.  
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        # run: ctest -C ${{env.BUILD_TYPE}}

      - name: Install
        # Build your program with the given configuration
        run: cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Zip
        run: |
          ls -al ./install/*
          tar -zcvf OatppServer.${{matrix.os}}.tar.gz ./install

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: OatppServer.${{matrix.os}}.tar.gz
          path: OatppServer.${{matrix.os}}.tar.gz
      
